/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaIO;

import java.awt.image.ImageObserver;
import java.io.*;
import java.util.Observer;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author 2class-005
 */
public class ImageCopyGUI extends javax.swing.JFrame {

    FileInputStream fis;
    FileOutputStream fos;
    
    public ImageCopyGUI() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        btCopy = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbTarget = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tf1.setText("C:/Myjava/pic.png");
        tf1.setBorder(javax.swing.BorderFactory.createTitledBorder("SourceFileName"));

        tf2.setBorder(javax.swing.BorderFactory.createTitledBorder("TargetFileName"));

        btCopy.setText("COPY");
        btCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	try {
            		btCopyActionPerformed(evt);
					
				} catch (Exception e) {
					e.printStackTrace();
				}
            }
        });

        lbTarget.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTarget.setText("여기에 카피된 이미지가 나올 예정");
        jScrollPane1.setViewportView(lbTarget);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addComponent(btCopy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf2)
                    .addComponent(tf1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCopy)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCopyActionPerformed(java.awt.event.ActionEvent evt) throws IOException{//GEN-FIRST:event_btCopyActionPerformed
        
    	//1. 원본파일명 얻어오기
    	String source= tf1.getText();
    	//2. 목적파일명 얻기
    	String target= tf2.getText();
    	//3. 유효성 체크
    	if(target.trim().isEmpty())
    	{
    		JOptionPane.showMessageDialog(this, "경로를 입력하세요");
    		return;
    	}
    	
    	// 확장자가 원본파일과 다르다면?
    	int beginIndex=source.lastIndexOf('.');
//    	System.out.println(beginIndex);
    	if(beginIndex==-1)
    	{
    		JOptionPane.showMessageDialog(this, "원본파일의 확장자명을 입력하셈");
    		return;
    	}
    	String ext= source.substring(beginIndex);
//    	System.out.println(ext);
    	
    	if(!target.endsWith(ext))
    	{
    		JOptionPane.showMessageDialog(this, "원본파일과 확장자가 일치하지 않습니다");
    		return;
    	}
    	
    	//4. stream 연결하여 반복문 돌려서 copy
    	int n=0, count=0;
    	
    	fis= new FileInputStream(source);
    	fos= new FileOutputStream(target);
    	while((n=fis.read())!=-1)
    	{
    		fos.write(n);
    		count++;
    	}
    	System.out.println(count+" bytes used");
    	
    	//5. 목적파일 lb에 나타내기
    	ImageIcon img= new ImageIcon(target);
    	lbTarget.setIcon(img);
    	lbTarget.setText(null);
    	//6. 닫기
    	fis.close();
    	fos.close();
    	
    }//GEN-LAST:event_btCopyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageCopyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageCopyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageCopyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageCopyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageCopyGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCopy;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTarget;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
}
